export enum LanguageLevel {
  BASIC = 'BASIC',
  CONVERSATIONAL = 'CONVERSATIONAL',
  WORKING_PROFICIENCY = 'WORKING_PROFICIENCY',
  FLUENT = 'FLUENT',
  NATIVE_BILINGUAL = 'NATIVE_BILINGUAL',
}

export enum Language {
  ENGLISH = 'ENGLISH',
  VIETNAMESE = 'VIETNAMESE',
}
